-- ═══════════════════════════════════════════════════════════════════
--  المرحلة 2 — توحيد قاعدة البيانات على Supabase
--  جدول السائقين + رموز OTP + أعمدة الرحلات الجديدة
--
--  📌 التنفيذ: Supabase → SQL Editor → New query → Run (مرة واحدة فقط).
--  ⚠️ قبل التنفيذ: تأكد من وجود جدول rides (أنشئ رحلة واحدة من التطبيق أولاً
--     أو استبدل public.rides باسم جدولك الفعلي).
-- ═══════════════════════════════════════════════════════════════════

-- ─────────────────────────── 1) جدول السائقين ───────────────────────
create table if not exists public.drivers (
  id            bigint generated by default as identity primary key,
  phone         text not null unique
                check (phone ~ '^\+2499[0-9]{8}$'),
  name          text,
  bank_account  text,
  vehicle_type  text,
  auth_token    text,                       -- رمز جلسة السائق (يُدار من الخادم)
  is_online     boolean not null default true,
  current_lat   double precision,           -- موقع السائق الحالي (اختياري)
  current_lng   double precision,
  avg_rating    double precision not null default 0,
  total_ratings integer not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists drivers_phone_idx      on public.drivers (phone);
create index if not exists drivers_auth_token_idx on public.drivers (auth_token);

-- ─────────────────────── 2) رموز التحقق OTP ─────────────────────────
create table if not exists public.otp_codes (
  id         bigint generated by default as identity primary key,
  phone      text not null,
  code_hash  text not null,                 -- SHA-256(phone:code) — لا نخزن الرمز نصاً
  expires_at timestamptz not null,
  attempts   integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists otp_codes_phone_idx on public.otp_codes (phone, created_at desc);

-- ─────────────── 3) أعمدة الرحلات الجديدة (pickup + driver_id) ──────
alter table public.rides
  add column if not exists driver_id bigint references public.drivers (id);

alter table public.rides
  add column if not exists pickup_lat double precision;

alter table public.rides
  add column if not exists pickup_lng double precision;

-- فهرس فلترة «الأقرب»: الحالة + الموقع
create index if not exists rides_status_pickup_idx
  on public.rides (status, pickup_lat, pickup_lng);

-- ملاحظة توحيد service_type:
-- القيم الموحّدة الآن: 'ركشة ركاب' | 'توك توك بضائع' | 'تكسي'
-- (القديم الإنجليزي ride/goods من طبقة Neon أُلغي مع حذف الطبقة)

-- ─────────────────────── 4) حماية الجداول (يُوصى به) ─────────────────
-- بعد نقل كل عمليات الرحلات إلى الخادم يمكن تفعيل RLS على كل الجداول:
--
-- alter table public.drivers  enable row level security;
-- alter table public.otp_codes enable row level security;
-- alter table public.rides    enable row level security;
--
-- وسياسات مقترحة بعدها (مسارات الخادم تستخدم Service Role فتتجاوز RLS):
-- create policy "anon can create pending ride"
--   on public.rides for insert to anon
--   with check (status = 'pending');
-- create policy "anon can read ride by id"
--   on public.rides for select to anon
--   using (true);  -- أو قيّدها حسب تدفق التطبيق
-- create policy "no anon update/delete on rides"
--   on public.rides for update to anon using (false);
-- create policy "no anon delete on rides"
--   on public.rides for delete to anon using (false);
-- (مفصّل في PHASE2-NOTES.md — القسم 8)
